version: '3.7'
services:

  proxy-service:
    image: nginx:1.17.10
    container_name: nginx_proxy
    depends_on:
      - react-client
      - user
      - events
      - feedback
    volumes:
      - ./server/proxy-service/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # User and Event related data.
  user-event-db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/:ro

  # Feedback and Analytics related data.
  feedback-analysis-db:
    image: mongo:latest
    container_name: feedback-analysis-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: feedback-analytics
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./server/m-db/init-db.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

  # React App: Front-End Service
  react-client:
    image: react-client
    container_name: react-client
    build:
      context: ./react-client
    depends_on:
      - user
      - events
      - feedback
    ports:
      - 3000:80
    restart: on-failure

  user:
    image: user
    container_name: user-service
    build:
      context: server/user
    ports:
      - 5001:5001
    restart: on-failure
    links:
      - user-event-db

  events:
    image: events
    container_name: event-service
    build:
      context: server/event
    ports:
      - 5002:5002
    restart: on-failure
    links:
      - user-event-db

  feedback:
    image: feedback
    container_name: feedback-service
    build:
      context: server/feedback
    ports:
      - 5003:5003
    restart: on-failure
    links:
      - feedback-analysis-db
